server:
  port: 8888

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/forever?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 100
  redis:
    host: 192.168.23.136
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        #jedis最大分配对象
        maxTotal: 10000
        #jedis最大保存idel状态对象数
        maxIdle: 500
        #jedis池没有对象返回时，最大等待时间
        maxWaitMillis: 10000
        testOnBorrow: true
        testOnReturn: true
        blockWhenExhausted: false
  data:
    mongodb:
      database: admin
      host: 192.168.23.136
      port: 27017
      username: amdin
      password: 123456
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
#  data:
#    mongodb:
#      uri: mongodb://192.168.23.133:27017/world

mybatis:
  mapper-locations: classpath:mapper/*.xml

hdfs:
  path: hdfs://192.168.25.136:9000
  username: root
